// Mocks generated by Mockito 5.4.6 from annotations
// in sobarba_mobile/test/ui/scheduling/view_models/scheduling_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sobarba_mobile/data/repositories/person_repository.dart' as _i5;
import 'package:sobarba_mobile/data/repositories/scheduling_repository.dart'
    as _i2;
import 'package:sobarba_mobile/domain/entities/person.dart' as _i6;
import 'package:sobarba_mobile/domain/entities/scheduling.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SchedulingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchedulingRepository extends _i1.Mock
    implements _i2.SchedulingRepository {
  MockSchedulingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Scheduling>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i3.Future<List<_i4.Scheduling>>.value(
              <_i4.Scheduling>[],
            ),
          )
          as _i3.Future<List<_i4.Scheduling>>);

  @override
  _i3.Future<_i4.Scheduling?> create(_i4.Scheduling? entity) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue: _i3.Future<_i4.Scheduling?>.value(),
          )
          as _i3.Future<_i4.Scheduling?>);

  @override
  _i3.Future<void> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i5.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.Person>> findAll() =>
      (super.noSuchMethod(
            Invocation.method(#findAll, []),
            returnValue: _i3.Future<List<_i6.Person>>.value(<_i6.Person>[]),
          )
          as _i3.Future<List<_i6.Person>>);
}
